name: flutter_sketchy_text
description: "Library to create sketchy text. with highlight, underline, strikethrough, circle and rectangle."
homepage: https://github.com/Wahab-Khan/flutter_sketchy_text/
repository: https://github.com/Wahab-Khan/flutter_sketchy_text/
topics:
  - sketchy
  - text
  - highlight
  - underline
  - animated

version: 0.1.0
license: MIT

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
